import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faPlay,
  faSearch,
  faMicrophone,
  faThumbsUp,
  faThumbsDown,
  faPlus,
  faCog,
  faShareAlt,
  faPaperPlane,
  faRedoAlt,
  faStickyNote,
  faTimes,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faEllipsisV,
  faWindowMinimize,
  faChevronDown,
  faChevronUp,
} from '@fortawesome/free-solid-svg-icons'
import { faThumbsDown as regFaThumbsDown, faTimesCircle } from '@fortawesome/free-regular-svg-icons'
library.add(
  faPlay,
  faSearch,
  faMicrophone,
  faThumbsUp,
  faThumbsDown,
  faPlus,
  regFaThumbsDown,
  faCog,
  faArrowUp,
  faShareAlt,
  faPaperPlane,
  faRedoAlt,
  faStickyNote,
  faTimes,
  faEllipsisV,
  faTimesCircle,
  faArrowDown,
  faArrowLeft,
  faWindowMinimize,
  faChevronDown,
  faChevronUp
)
export default library
export const iconsList = {
  'fas play': 'fas play',
  'fas cog': 'fas cog',
  'fas paper-plane': 'fas paper-plane',
  'fas thumbs-up': 'fas thumbs-up',
  'fas thumbs-down': 'fas thumbs-down',
  'far thumbs-down': 'far thumbs-down',
  'fas redo-alt': 'fas redo-alt',
  'fas plus': 'fas plus',
  'fas share-alt': 'fas share-alt',
  'fas search': 'fas search',
  'fas sticky-note': 'fas sticky-note',
  'fas microphone': 'fas microphone',
  'fas times': 'fas times',
  'fas ellipsis-v': 'fas ellipsis-v',
  'far times-circle': 'far times-circle',
  'fas arrow-up': 'fas arrow-up',
  'fas arrow-down': 'fas arrow-down',
  'fas arrow-left': 'fas arrow-left',
  'fas chevron-up': 'fas chevron-up',
  'fas chevron-down': 'fas chevron-down',
}
