export interface ThemeColors {
  primaryWhite: string
  primarySenderBG: string
  primaryBadge: string
  primaryResponse: string
  primaryBrightResponse: string
  primary: string
  primaryLinks: string
  primaryBackground: string
  primaryText: string
  primaryDark: string
  primaryAccent: string
  secondaryRate: string
  primaryDivider: string
  primaryExampleBackground: string
  primaryButton: string
  secondaryButton: string
  primaryPlaceholder: string
  primaryButtonHover: string
  primaryDateDivider: string
  primaryRatingElement: string
  primaryExample: string
  primaryBlack: string
  primaryGray: string
  primaryDashed: string
  primaryFileBackground: string
  primaryHeaderButtonHover: string
  primaryHeaderButtonActive: string
  primaryChooseFileButtonHover: string
}
